Add test trigger and change the SDK location for Upload and Download
Signed-off-by: Hasibur Rahman Mohammed <hasiburr@qti.qualcomm.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -8,9 +8,7 @@ jobs:
   process_url:
     outputs:
       build_url: ${{ steps.get_build_url.outputs.result }}
-    runs-on:
-      group: GHA-Audioreach-SelfHosted-RG
-      labels: [ self-hosted, audior-prd-u2204-x64-large-od-ephem ]
+    runs-on: ubuntu-latest
     steps:
       - name: Download presigned URL
         id: download_url
@@ -30,7 +28,7 @@ jobs:
             console.log(url)
             return url
 
-  prepare-job-list:
+  submit_lava:
     runs-on:
       group: GHA-Audioreach-SelfHosted-RG
       labels: [ self-hosted, audior-prd-u2204-x64-large-od-ephem ]
@@ -53,52 +51,49 @@ jobs:
       - name: "List jobs"
         id: listjobs
         run: |
-          JOBFILES=$(find ci/lava/ -name *.yaml)
-          JOBFILES=$(echo "$JOBFILES" | sed -e "s/^/\"/" | sed -e "s/$/\",/" | tr -d "\n" | sed -e "s/.$//")
-          JOBFILES="[${JOBFILES}]"
-          J=$(jq -cn --argjson jobfiles "$JOBFILES" '{target: $jobfiles}')
-          echo "jobmatrix=$J" >> $GITHUB_OUTPUT
-          echo "Preparing testjob files"
+          target_file="ci/lava/qcs6490-rb3gen2-core-kit/boot.yaml"
+          if [ ! -f "$target_file" ]; then
+            echo "Target file $target_file does not exist."
+            echo "target_file=" >> "$GITHUB_OUTPUT"
+            exit 1
+          fi
 
-  submit-job:
-    needs: [process_url, prepare-job-list]
-    runs-on:
-      group: GHA-Audioreach-SelfHosted-RG
-      labels: [ self-hosted, audior-prd-u2204-x64-large-od-ephem ]
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.prepare-job-list.outputs.jobmatrix) }}
-    steps:
-      - name: Clone repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          repository: Audioreach/meta-ar
-
-      - name: "Update test definition ${{ matrix.target }}"
-        run: |
-          TARGET=${{ matrix.target }}
+          TARGET=${target_file}
           FIND_PATH="${TARGET#*/}"
           DEVICE_TYPE_PATH="${FIND_PATH%/*}"
           DEVICE_TYPE="${DEVICE_TYPE_PATH#*/}"
           BUILD_FILE_NAME="core-image-base-qcs6490-rb3gen2-core-kit.rootfs.qcomflash.tar.gz"
           BUILD_DOWNLOAD_URL="${{ needs.process_url.outputs.build_url }}"
-          sed -i "s|{{DEVICE_TYPE}}|${DEVICE_TYPE}|g" "${{ matrix.target }}"
-          sed -i "s|{{GITHUB_SHA}}|${GITHUB_SHA}|g" "${{ matrix.target }}"
+          sed -i "s|{{DEVICE_TYPE}}|${DEVICE_TYPE}|g" "${target_file}"
+          sed -i "s|{{GITHUB_SHA}}|${GITHUB_SHA}|g" "${target_file}"
           ESCAPED_URL=$(echo "$BUILD_DOWNLOAD_URL" | sed 's/[&/?=]/\\&/g')
-          sed -i "s|{{BUILD_DOWNLOAD_URL}}|$ESCAPED_URL|g" "${{ matrix.target }}"
-          sed -i "s|{{BUILD_FILE_NAME}}|${BUILD_FILE_NAME}|g" "${{ matrix.target }}"
-          sed -i "s|{{GITHUB_RUN_ID}}|${GITHUB_RUN_ID}|g" "${{ matrix.target }}"
-          cat "${{ matrix.target }}"
+          sed -i "s|{{BUILD_DOWNLOAD_URL}}|$ESCAPED_URL|g" "${target_file}"
+          sed -i "s|{{BUILD_FILE_NAME}}|${BUILD_FILE_NAME}|g" "${target_file}"
+          sed -i "s|{{GITHUB_RUN_ID}}|${GITHUB_RUN_ID}|g" "${target_file}"
+          cat "${target_file}"
+          echo "target=${target_file}" >> "$GITHUB_OUTPUT"
 
-      - name: Submit ${{ matrix.target }}
+      - name: Test with LAVA
+        if: ${{ steps.listjobs.outputs.target != '' }}
+        id: submit_job
         timeout-minutes: 20
         uses: foundriesio/lava-action@v6
         with:
-          lava_token: ${{ secrets.LAVA_TOKEN }}
+          lava_token: ${{ secrets.LAVATOKEN }}
           lava_url: 'lava.infra.foundries.io'
-          job_definition: ${{ matrix.target }}
+          job_definition: ${{ steps.listjobs.outputs.target }}
           wait_for_job: true
           fail_action_on_failure: false
           save_result_as_artifact: true
           save_job_details: true
+
+      - name: Update Summary
+        if: success() || failure()
+        run: |
+          if [ "${{ steps.submit_job.outcome }}" == "success" ]; then
+            echo "## Test Job Summary" >> $GITHUB_STEP_SUMMARY
+            echo ":heavy_check_mark: Test job completed successfully." >> $GITHUB_STEP_SUMMARY
+          else
+            echo "## Test Job Summary" >> $GITHUB_STEP_SUMMARY
+            echo ":x: Test job failed." >> $GITHUB_STEP_SUMMARY
+          fi
